# Generated by Django 3.0.7 on 2020-10-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_rand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='catname',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='writer',
            field=models.CharField(max_length=255),
        ),
    ]
