# Generated by Django 3.0.7 on 2020-10-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201016_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rand',
            field=models.TextField(default=0, max_length=100),
        ),
    ]
