# Generated by Django 3.0.7 on 2020-10-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_auto_20201016_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'get_latest_by': ['-priority', 'order_date'], 'ordering': ['name'], 'verbose_name': 'Bảng Thể Loại', 'verbose_name_plural': 'Bảng Thể Loại'},
        ),
    ]
