# Generated by Django 3.0.7 on 2020-10-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcat',
            name='catname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
