# Generated by Django 3.0.7 on 2020-10-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='txt',
            field=models.CharField(max_length=255),
        ),
    ]
