# Generated by Django 3.0.7 on 2020-10-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0002_auto_20201016_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='txt',
            field=models.CharField(max_length=200),
        ),
    ]
