# Generated by Django 3.0.7 on 2020-10-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0003_auto_20201016_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='txt',
            field=models.CharField(max_length=255),
        ),
    ]
